services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile.txt
    container_name: spring-app
    ports:
      - "8081:8080"
    volumes:
      - /d/CardTestLogs:/app/logs
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/card_test
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
    networks:
      - card-network

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: card_test
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./card-test.sql:/docker-entrypoint-initdb.d/card-test.sql
    networks:
      - card-network

volumes:
  postgres-data:

networks:
  card-network:
    driver: bridge
